# Generated by Django 4.0.6 on 2022-08-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=500)),
                ('student_age', models.IntegerField()),
                ('student_school', models.CharField(max_length=1000)),
            ],
        ),
    ]
